---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
  - name: centos-8
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - "recipe[fixture::port]"
      - "recipe[fixture::service]"
      - "recipe[fixture::masquerade]"
    attributes:

  - name: rich_rule
    run_list:
      - "recipe[fixture::rich_rule]"
    attributes:
